#!/bin/sh
# curl -s https://raw.githubusercontent.com/nikalang/setup/master/setup | sh
echo \
"
 .-----------------. .----------------.  .----------------.  .----------------. 
| .--------------. || .--------------. || .--------------. || .--------------. |
| | ____  _____  | || |     _____    | || |  ___  ____   | || |      __      | |
| ||_   \|_   _| | || |    |_   _|   | || | |_  ||_  _|  | || |     /  \     | |
| |  |   \ | |   | || |      | |     | || |   | |_/ /    | || |    / /\ \    | |
| |  | |\ \| |   | || |      | |     | || |   |  __'.    | || |   / ____ \   | |
| | _| |_\   |_  | || |     _| |_    | || |  _| |  \ \_  | || | _/ /    \ \_ | |
| ||_____|\____| | || |    |_____|   | || | |____||____| | || ||____|  |____|| |
| |              | || |              | || |              | || |              | |
| '--------------' || '--------------' || '--------------' || '--------------' |
 '----------------'  '----------------'  '----------------'  '----------------' 
"

if [ -z "$NIKA_HOME" ]; then
    NIKA_HOME="$HOME/.nika"
fi

export NIKA_HOME="$NIKA_HOME"

git clone https://github.com/nikalang/util.git "$NIKA_HOME/repository/util"
git clone https://github.com/nikalang/bin.git  "$NIKA_HOME/repository/bin"

export PATH="$NIKA_HOME/repository/bin:$PATH"