#!/bin/sh
echo \
"
 .-----------------. .----------------.  .----------------.  .----------------. 
| .--------------. || .--------------. || .--------------. || .--------------. |
| | ____  _____  | || |     _____    | || |  ___  ____   | || |      __      | |
| ||_   \|_   _| | || |    |_   _|   | || | |_  ||_  _|  | || |     /  \     | |
| |  |   \ | |   | || |      | |     | || |   | |_/ /    | || |    / /\ \    | |
| |  | |\ \| |   | || |      | |     | || |   |  __'.    | || |   / ____ \   | |
| | _| |_\   |_  | || |     _| |_    | || |  _| |  \ \_  | || | _/ /    \ \_ | |
| ||_____|\____| | || |    |_____|   | || | |____||____| | || ||____|  |____|| |
| |              | || |              | || |              | || |              | |
| '--------------' || '--------------' || '--------------' || '--------------' |
 '----------------'  '----------------'  '----------------'  '----------------' 
"

if [ -z "$NIKA_HOME" ]; then
    NIKA_HOME="$HOME/.nika"
fi

export NIKA_HOME="$NIKA_HOME"

echo \
"
Setting up Nika project...
"

mkdir -p "$NIKA_HOME/local"

git clone -q https://github.com/nikalang/util.git  "$NIKA_HOME/util"
git clone -q https://github.com/nikalang/bin.git   "$NIKA_HOME/bin"
git clone -q https://github.com/nikalang/setup.git "$NIKA_HOME/setup"

export PATH="$NIKA_HOME/bin:$PATH"

echo \
"
export NIKA_HOME=\"$NIKA_HOME\"
export PATH=\"\$NIKA_HOME/bin:\$PATH\"
" >> "$HOME/.profile"

echo \
"
Type the following to start using Nika CLI (or restart the shell):

  . ~/.profile
"
